#!/usr/bin/env python3


# Programs the target device. By default the hex file generated by
# build_target.sh is used but it's possible to specify another one.


from common import *

import argparse



def main():
    # parse args

    default_firmware_file = "../target/simpleserial-chacha/simpleserial-chacha-CWLITEARM.hex"

    parser = argparse.ArgumentParser(description="Program target device", formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument("FW_FILE", nargs="?", default=default_firmware_file, help="firmware file")

    args = parser.parse_args()


    # program the target

    scope, _, prog = init_scope()
    cw.program_target(scope, prog, args.FW_FILE)



if __name__ == "__main__":
    main()

